name: arb_glue
description: |
  ARB Glue is a tool that merges multiple files into one single [ARB] format file,
  facilitating the management of internationalization resources.
version: 0.0.2
homepage: https://github.com/evan361425/flutter-arb-glue

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  args: ^2.4.2
  logging: ^1.2.0
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
