name: arb_glue
description: "Concatenate multiple arb files into one."
version: 0.0.1
homepage: https://github.com/evan361425/flutter-arb-glue

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  args: ^2.4.2
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
