name: Publish package

on:
  # Pub.dev only allows automated publishing from GitHub Actions
  # when the workflow is triggered by pushing a git tag to GitHub.
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  # https://github.com/dart-lang/setup-dart/blob/main/.github/workflows/publish.yml
  publish:
    name: "Publish to pub.dev"
    permissions:
      id-token: write
    # Specify the github actions deployment environment
    environment: pub.dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: "stable"
      # Minimal package setup and dry run checks.
      - name: Install dependencies
        run: dart pub get
      - name: Publish - dry run
        run: dart pub publish --dry-run
      # Publishing..., it will keep asking
      - name: Publish to pub.dev
        run: dart pub publish --force
